### ISSUE TITLE
Duplicated connections when using StartStopBinderLifecycle which causes News events (probably other things also) to be fired several times 

### ISSUE THREAD

**Issue by timopl** [badoo/MVICore#120]
Hello! 

I've faced a problem while trying to use `StartStopBinderLifecycle` with fragments. 
When going back and forth between fragments, binding happens every time and it creates duplicated connections and subscriptions. After that NewsListener's accept method called 2 times. (I'm not sure if reducer or actor are affected)

<img width="1371" alt="Снимок экрана 2019-12-26 в 12 07 20" src="https://user-images.githubusercontent.com/1262098/71468881-8110c300-27d8-11ea-8043-95ef12faf142.png">

P.S. `.distrinctUntilChanged()` doesn't help.

Thanks!

**Comment by timopl** [comment]
I think this might be related https://github.com/badoo/MVICore/issues/39

**Comment by timopl** [comment]
False alarm! 
This behavior was caused by my mistake: I've called `bindings.setup(this)` in `onViewCreated` method of fragment, which basically caused duplication of connections.

I'm not sure if the library should consider uniqueness of connections tho.

**Comment by ProbablyBatman** [comment]
Where did you end up calling bind in the fragment? I'm having the same issue.

**Comment by ShikaSD** [comment]
Hey @ProbablyBatman,
you probably want to call it in `onCreate`, so that the bindings are created only once for each fragment instance.
