### ISSUE TITLE
MVICore File Templates plugin not compatible with Android Studio 4.1

### ISSUE THREAD

**Issue by MairwunNx** [badoo/MVICore#135]
I've a problem with installing mvi core file templates plugin, I've downloaded plugin from [here](https://badoo.github.io/MVICore/extras/templategeneratorplugin/).

*Fun fact, my collegue also tried to install that plugin and he've the same version of android studio and got success these LOL*.

![image](https://user-images.githubusercontent.com/39625750/96842677-01826d80-1456-11eb-92a3-bd00f079bd3d.png)

![image](https://user-images.githubusercontent.com/39625750/96842802-2840a400-1456-11eb-842e-42dcb740ce21.png)

**Comment by Nublo** [comment]
@MairwunNx I was looking into this problem and found out, that plugin itself should be working fine.
And same problem is similar to [other plugins](https://stackoverflow.com/questions/64347831/android-studio-4-1-plugin-error-plugin-is-incompatible-supported-only-in-int).

I found an easy fix to this problem. Remove the plugin manually from:
~/Library/Application Support/Google/AndroidStudio4.1/plugins
And then install it again.

Probably you already had this plugin installed on the previous version and then migrated to the 4.1 Android Studio.
And your friend installed plugin on 4.1, so didn't encounter this problem.

**Comment by MairwunNx** [comment]
@Nublo thanks, I've tried do this, but plugin still incompatible with Android Studio 4.1

**Comment by Nublo** [comment]
@MairwunNx, I update plugin adding missing depends line to the manifest.
Double checked with a team member who had similar issue on Android Studio 4.1. 
Should work now.

Try to uninstall the plugin again (and remove from AS plugin folders as well)
And install the new version, after restarting Android Studio it should work.

**Comment by MairwunNx** [comment]
@Nublo thanks, now it's works! Have a nice day.
