### ISSUE TITLE
Is it really Actors work in async mode?

### ISSUE THREAD

**Issue by ValeriusGC** [badoo/MVICore#55]
Hi there.
First: when i place Logger in the so-called `async actor` 
```
fun loadRandomImage(): Observable<Response> {
          Log.d("!@#", "thread is ${Thread.currentThread().name}")
            return service.getRandomImage()
                .randomlyThrowAnException()
                .observeOn(AndroidSchedulers.mainThread())
        }
```
i got 
`com.badoo.mvicoredemo D/!@#: thread is main`
Second: when i try to emulate delay with
```
is LoadNewImage -> loadRandomImage()
                .delay(1000, TimeUnit.MILLISECONDS)
                .map {
                    LoadedImage(it.url!!) as Effect
                }
                .startWith(just(StartedLoading))
                .onErrorReturn { ErrorLoading(it) }
```
i got
`Caused by: java.lang.AssertionError: Not on same thread as previous verification` from your 
`class SameThreadVerifier`

what do i wrong?

**Comment by zsoltk** [comment]
@ValeriusGC in your first example your logging call is executed before the observable is created, and has no relevance over its execution.

However, your main problem is that when you call ```delay```, it operates on the computation scheduler by default (check documentation for rxjava), and in that example you are not bringing it back to the main thread. The line ```.observeOn(AndroidSchedulers.mainThread())``` is there, but if you check the order, it's invoked in ```loadRandomImage()```, and you call ```delay()``` after that point.

MVICore doesn't care about a main thread, just that your Feature should be invoked on the same thread as it was created on. So probably you created it on the main thread but after delay you are left on the computation thread.

**Comment by ValeriusGC** [comment]
you are right... my fault. Novichok (R)
