### ISSUE TITLE
Lifecycle bound connections can be subscribed several times

### ISSUE THREAD

**Issue by ShikaSD** [badoo/MVICore#60]
The connections using repeatable Android lifecycles (Resume-Pause, Start-Stop) can be subscribed several times, as activity callbacks are triggered after onNewIntent.
Possible solutions:  
- have lifecycle subscribed in binder with distinctUntilChanged
- apply distinctUntilChanged for Android lifecycles
- ???

**Comment by zsoltk** [comment]
Good point. Can we think of any practical use case where several consecutive lifecycle start signals make sense before an end signal? Because if not, then we can just add ```distinctUntilChanged``` on signals inside the Binder automatically.

**Comment by ShikaSD** [comment]
Even if there is any use case for this, I still think that it makes sense to add distinctUntilChanged to the binder. Will make a PR.
