### ISSUE TITLE
Issues with EditText and suggestions

### ISSUE THREAD

**Issue by BraisGabin** [badoo/MVICore#84]
Sorry, this is a question more than an issue but I since there isn't a mail list or similar I'll write it here. Please tell me if this is not the correct place.

We use MVICore in our app and we are having two problems that I'd like to share to see if we are doing something wrong, we are missing something or they are really issues so we can create a PR to fix them:

- The first one appears with the suggestions in a search view. When you are type a character we launch a wish. This wish ends with a call to the server to get the suggestions to autocomplete. The problem is that while the user keep typing it launch more wishes and there is no way to "dispose" the previous calls. In this case we have race conditions. Normally the last call is the last one that we receive so all seems to work, but we see edge cases where we receive those responses in different orther. How do you handle this? With rxJava is just a `switchMap` but we can't use it here.
- The second problem is related with the `EditText`. When you start typing in the EditText you send wishes with that data. And you generates a new state with that data. And in the render you should set that data. If you do so you get an infinite loop because you are changing the EditText again so it launch another wish... Ok, this problem is kind of easy to solve: `distinctUntilChange`. The problem now is that we have an `observeOn(mainScheduler)` so we lose one frame to sync the data. If the user types fast (not really fast, just fast) we are setting an "old text" so the user loses the last typed character. Here we are fighting against the framework and losing. How do you handle this problem?

**Comment by amihusb** [comment]
Hi, about first problem look at similar [issue](https://github.com/badoo/MVICore/issues/68). What about second, i used this typical solution:
```kotlin
private val watcher = object : TextWatcher {...}

// inside render
editText.removeTextChangedListener(watcher)
editText.text = someText
editText.addTextChangedListener(watcher)
```

**Comment by kyhule** [comment]
@BraisGabin How are you creating a wish from the user's input on the SearchView? If you are creating an Observable with something like RxBindings, you should be able to use the `debounce` operator to prevent excess calls to your server. Here is an example which also filters out inputs that are less than 3 characters.
```
val searchQueryObservable = searchView.queryTextChanges()
	.filter { it.length() > 2 }
	.debounce(100, TimeUnit.MILLISECONDS)
```
This should be good enough to reduce the race condition but if you want to dispose of the previous in-flight service call, you could do something like this https://github.com/badoo/MVICore/issues/68#issuecomment-472109537.

**Comment by ShikaSD** [comment]
@BraisGabin 
This is the right place to ask questions as well (although we probably should start labeling those).
Now to your questions:

First, as people here already mentioned, there's a possible solution [in another question](https://github.com/badoo/MVICore/issues/68#issuecomment-472109537). Theoretically, request cancellation can be extracted to a lower level (e.g. dataSource), but I personally prefer to have all the logic in the feature, as it tends to get messy otherwise.

Second, you can use the method suggested by @amihusb, which is rather standard now (such is Android world), or use something like this:
```kotlin
if (model.text != editText.text) editText.text = model.text
```
As for the `observeOn` with `mainScheduler`, I am not sure how you update the state, but maybe solution like this will work for you:
```kotlin
when (wish) {
    is Wish.TextUpdate -> 
        dataSource.request(wish.text)
              .map { /* effect */ }
              .observeOn(mainScheduler)
              .startWith(Effect.TextUpdated(wish.text))
}
```
What happens here is `Effect.TextUpdated` updates the value set to the `EditText`. It is separated from query request and is executed before the rest of the observable, effectively in the same execution frame.

**Comment by BraisGabin** [comment]
Ok, the first question is solved with https://github.com/badoo/MVICore/issues/68#issuecomment-472109537 (Thanks @kyhule to point it out)

The second is more tricky. The infinite loop is easy to solve with `distinctUntilChange`. 

The main problem is the user getting a bad experience while she is typing (losing characters). Right now we were adding an `observeOn(mainScheduler)` at the end of the `when`. Probably we should stop doing that and handle this per wish... I'll try that out and check if it works. 

Thanks! I'll update if it works or not.

**Comment by BraisGabin** [comment]
Sorry for the delay, but I wanted to check this properly. If I use the  idea of @ShikaSD and I don't change the thread all works perfectly. So thanks, that did the trick!

With this aprouch appears a new issue: You can't use `debounce` like this: `editText.afterTextChangeEvents().debounce(/*...*/)` because `debound` changes the thread. I did the trick in the Actor (and it have sense, the view should not know about refresh rates):

```kotlin
interruptSignal.accept(Unit)
return Single.just(Unit)
  .delay(300, TimeUnit.MILLISECONDS) // this change the thread but it's not a problem here.
  .flatMapPublisher {
    useCase.requestData(action.query)
  }
  .takeUntil(interruptSignal.toFlowable(BackpressureStrategy.LATEST))
  .map { /* ... */ }
  .observeOn(mainScheduler)
  .startWith(Effect.QueryUpdated(action.query))
```

_Side note: Don't set the text again to your editText if it's already set:_
```kotlin
if (editText.text.toString() != value) {
  editText.setText(value)
}
```
