### ISSUE TITLE
Shouldn't DiffStrategy return true if the values are equal?

### ISSUE THREAD

**Issue by arkivanov** [badoo/MVICore#93]
At the moment `DiffStrategy` return true if the values are different. Perhaps they should be inverted to be consistent with normal comparators. Also Rx `distingUntilChanged` lambdas return true if values are equal. Inverted behavour is confusing.

**Comment by zsoltk** [comment]
I think it makes sense following from its name: it's a diff strategy, not an equals strategy, so it would be more confusing the other way. With `distinctUntilChanged` you don't actually pass in a boolean expression to evaluate, only a value, so it also makes sense that it checks for equality. I can agree to such an approach here as well, but I believe @ShikaSD wanted to have boolean expressions for multiple fields in some complex cases, and there you can't express the same thing with equality check as with a diff check.

**Comment by arkivanov** [comment]
What I mean is that purpose of `distinctUntilChanged` is to emit values only if theay are _different_, and its predicate accepts two values (old and new) and returns `true` if they are _equal_. Absolutely same as `ModelWatcher`, it diffs and acts only if values are different. That's why it is confusing to me.

**Comment by ShikaSD** [comment]
I believe we had a lot of discussions regarding whether the `diffStrategy` should be inverted or not. I don't remember the exact details, but we settled on the current approach.
Probably we can simplify it for the end user by renaming the field to `comparator` and returning whether the values are the same, as RxJava does.

**Comment by ShikaSD** [comment]
@arkivanov @zsoltk 
While playing around with inverted `diffStrategy`, which return **true** whenever values are **equal**, I have found this issue:
```
data class Model(
    val int: Int = 0,
    val list: List<String> = listOf()
)

val intOrList = { old, new -> old.int == new.int && old.list == new.list }
watch({ it }, intOrList) { }
```
This API is completely counterintuitive, as it makes you use `&&` to implement `or` relation.
Using current implementation:
```
val intOrList = { old, new -> old.int != new.int || old.list != new.list }
```
Although we have the same problem in `distinctUntilChanged`, the question is whether it is desired here.

**Comment by arkivanov** [comment]
I actually don't any issues with the first variant. For me the second variant is very confusing and harder to read.

**Comment by arkivanov** [comment]
I agree that it should be a predicate, not equality comparator. So return true when values are different is logically correct. However I believe it's better to keep consistency with existing things.
Same situation "filter": based on nature of physical name it should
