### ISSUE TITLE
Best way to use DialogFragment

### ISSUE THREAD

**Issue by simonvar** [badoo/MVICore#96]
I use DialogFragment with the common feature of parent Fragment and another ui event transformer.

```kotlin
class Fragment : 
SourceFragment<FragmentUiEvent>(), 
Consumer<FragmentViewModel> {
...
    private val feature by scope.inject<Feature>
...
```

```kotlin
class Dialog : 
SourceDialog<DialogUiEvent>(), 
Consumer<DialogViewModel> {
...
    private val feature by scope.inject<Feature>
...
```
But i not sure that is the best way of using dialogs.

Can somebody show example of using dialogs with MVICore?

**Comment by ShikaSD** [comment]
Hey @simonvar 
In general, there's nothing wrong in using feature as a single source of truth for both Dialog and Fragment.
I am not sure what kind of operations you do in `Dialog`. If it is just a simple `Ok` - `Cancel` one, I would handle all the interaction with the `Feature` in the `Fragment`. For example, you can show/hide dialog using `News` and pass `Wish` on button callback.

**Comment by simonvar** [comment]
Thanks for answer!
